import "./globals.css";
import Navbar from "@/components/Navbar";
import AllPageList from "@/components/AllPageList";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`px-2.5 sm:px-8 md:px-10 lg:px-16 min-h-screen bg-bg_color  `}
      >
        <div className='flex flex-col'>
          <Navbar />
          <div className="sm:hidden block">

          <AllPageList />
          </div>
          <main className=''>{children}</main>
        </div>
      </body>
    </html>
  );
}
